### ISSUE TITLE
uuid version and support index.js require seems not working 

### ISSUE THREAD

**Issue by celexon** [shopware/e2e-testsuite-platform#145]
After a fresh installation of the test suite, I kept getting the error that the uuid/v4 module cannot be found. After installing uuid 3.3.2 it worked then. Either the version of uuid must be set to 3.3.x or the require in the cypress/support/index.js has to be modified from

const uuid = require('uuid/v4');

To

const { v4: uuidv4 } = require('uuid');

**Comment by jleifeld** [comment]
This problem should be fixed with the latest release 3.0.2
